GET http://localhost:3000/api/users
###
GET http://localhost:3000/api/events
###
POST http://localhost:3000/api/reservations
Content-Type: application/json

{
    "event_id": "65f678c8babb3505aa591c9b",
    "user_id": "65ef7f8524a928f9e39f6615",
    "ticket_quantity": 4,
    "status": "confirmed",
    "total_price": 120
}
// events : 65f678c8babb3505aa591c99
//users: 65ef7f8524a928f9e39f6615
### 
GET  http://localhost:3000/api/reservations

### 
GET  http://localhost:3000/api/users/65ef7f8524a928f9e39f6615/reservations

### 
GET http://localhost:3000/api/reservations/65ef7f8524a928f9e39f6615/byIdUser

###
GET http://localhost:3000/api/images/gilbertosantarosa.jpg
###
GET http://localhost:3000/api/events
 